captcha/urls.py
from django.conf.urls.defaults import *
urlpatterns = patterns('',
    (r'(?P<token_uid>\w+).jpg$','captcha.views.captcha_image'),
)


member/urls.py
from django.conf.urls.defaults import *
from ddtcms.home.views import common_dict
from ddtcms.member.models import Profile,Resume

common_dict.update({'app_label':'member',    })
    
    
member_dict = {
'queryset': Profile.objects.all(),
'extra_context':common_dict,
'template_name':'member/index.html',
}


pages_dict = {
'queryset': Profile.objects.all(),
'extra_context':common_dict,
'paginate_by':1,
}


urlpatterns = patterns('',
    (r'^$',                            'django.views.generic.list_detail.object_list', member_dict),


)

tagging/urls.py
from django.conf.urls.defaults import *
from tagging.views import tagged_object_list

urlpatterns = patterns('',
    #(r'^$',                    'django.views.generic.date_based.archive_index', todo_dict),
    url(r'^$',                  'tagging.views.index', name='tagging-index'),
    url(r'^(?P<tag>[-\w]+)/$',  'tagging.views.by_tag',name='tagged_object_list'),
)

urlpatterns += patterns('',
    url(r'^tr/(\d+)/(\w+)/$', 'django.views.defaults.shortcut', name='tag-url-redirect'),
)

urls.py
from django.conf.urls.defaults import *
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from django.views.generic.simple import direct_to_template
from django.contrib.sitemaps import FlatPageSitemap, GenericSitemap
from ddtcms.blog.sitemaps import BlogSitemap
from ddtcms.blog.models import Blog

from ddtcms.member.views import get_profiles


from django.contrib.contenttypes.models import ContentType
from django.http import HttpResponseRedirect

def export_selected_objects(modeladmin, request, queryset):
    selected = request.POST.getlist(admin.ACTION_CHECKBOX_NAME)
    ct = ContentType.objects.get_for_model(queryset.model)
    return HttpResponseRedirect("/export/?ct=%s&ids=%s" % (ct.pk, ",".join(selected)))

admin.site.add_action(export_selected_objects)

info_dict = {
    'queryset': Blog.objects.all(),
    'date_field': 'pub_date',
}

sitemaps = {
    'flatpages': FlatPageSitemap,
    'blog': BlogSitemap,
}






from ddtcms import settings

urlpatterns = patterns('',
    # Example:
    # (r'^ddtcms/', include('ddtcms.foo.urls')),
    (r'^',                     include('ddtcms.home.urls')),
    (r'^(?i)news/',            include('ddtcms.news.urls')),
    (r'^(?i)saying/',          include('ddtcms.saying.urls')),
    (r'^(?i)forum/',           include('ddtcms.forum.urls')),
    (r'^(?i)faq/',             include('ddtcms.faq.urls')),
    (r'^(?i)polls/',           include('ddtcms.polls.urls')),
    (r'^(?i)blog/',            include('ddtcms.blog.urls')),
    (r'^(?i)book/',            include('ddtcms.book.urls')),
    (r'^(?i)captcha/',         include('ddtcms.captcha.urls')),
    (r'^(?i)notice/',          include('ddtcms.notice.urls')),
    (r'^(?i)link/',            include('ddtcms.link.urls')),
    (r'^(?i)people/',          include('ddtcms.people.urls')),
    (r'^(?i)todo/',            include('ddtcms.todo.urls')),
    (r'^(?i)guestbook/',       include('ddtcms.guestbook.urls')),
    
    (r'^(?i)member/',          include('ddtcms.member.urls')),
    (r'^(?i)member/$',         direct_to_template, {'extra_context': { 'profiles': get_profiles }, 'template': 'member/front.html' }),
    
    (r'^(?i)photologue/',      include('photologue.urls')),
    (r'^(?i)photologue/$',     direct_to_template, {'template': 'photologue/index.html' }),

    (r'^(?i)attachments/',     include('attachments.urls')),
    (r'^(?i)tags/',            include('tagging.urls')),
    
    
    # serve static medias
    (r'^(?i)media/(?P<path>.*)$',      'django.views.static.serve',{'document_root': settings.MEDIA_ROOT}),
    (r'^(?i)themes/(?P<path>.*)$',     'django.views.static.serve',{'document_root': settings.STATIC_THEMES}),
    (r'^(?i)images/(?P<path>.*)$',     'django.views.static.serve',{'document_root': settings.STATIC_IMAGE}),
    (r'^(?i)css/(?P<path>.*)$',        'django.views.static.serve',{'document_root': settings.STATIC_CSS}),	
    (r'^(?i)js/(?P<path>.*)$',         'django.views.static.serve',{'document_root': settings.STATIC_JS}),    		
    (r'^(?i)upload/(?P<path>.*)$',     'django.views.static.serve',{'document_root': settings.STATIC_UPLOAD}),
    (r'^(?i)editor/(?P<path>.*)$',     'django.views.static.serve',{'document_root': settings.STATIC_EDITOR}),
    (r'^(?i)attachment/(?P<path>.*)$', 'django.views.static.serve',{'document_root': settings.STATIC_UPLOAD+"attachment/"}),
    
    	    
    (r'^(?i)sitemap.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),    
    (r'^(?i)sitemap-(?P<section>.+).xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    
    # user django comments system    
    (r'^(?i)comments/', include('django.contrib.comments.urls')),
    
    # Uncomment the admin/doc line below and add 'django.contrib.admindocs'
    # to INSTALLED_APPS to enable admin documentation:
    (r'^admin/doc/', include('django.contrib.admindocs.urls')),
    
    # Uncomment the next line to enable the admin:
    (r'^admin/', include(admin.site.urls)),


)


# Serves media content. WARNING!! Only for development uses.
# On production use lighthttpd for media content.
if settings.DEBUG:

    # Delete the first trailing slash, if any.
    if settings.MEDIA_URL.startswith('/'):
        media_url = settings.MEDIA_URL[1:]
    else:
        media_url = settings.MEDIA_URL

    # Add the last trailing slash, if have not.
    if not media_url.endswith('/'):
        media_url = media_url + '/'

    urlpatterns += patterns('',
        (r'^' + media_url + '(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}
        ),
    )

member/models.py
# coding=UTF-8
from django.db import models
from django.contrib.sites.models import Site
from django.contrib.auth.models import User
from django.template.defaultfilters import slugify
from django.utils.translation import ugettext as _
from django.template import loader, Context
from django.core.urlresolvers import reverse
from django.core.mail import send_mail
from django.conf import settings
from django.core.exceptions import ImproperlyConfigured
from ddtcms.member.countries import CountryField
import datetime
import cPickle as pickle
import base64
import os.path
try:
    from PIL import Image, ImageFilter
except ImportError:
    import Image, ImageFilter

from forum.models import Post
from blog.models import Blog

AVATAR_SIZES = (128, 96, 64, 48, 32, 24, 16)

class UserResumeNotAvailable(Exception):
    pass
    
class UserFavouriteNotAvailable(Exception):
    pass
    
class UserConfigurationNotAvailable(Exception):
    pass




class BaseProfile(models.Model):
    """
    User profile model
    """

    user = models.ForeignKey(User, unique=True)
    date = models.DateTimeField(default=datetime.datetime.now)
    country = CountryField(null=True, blank=True,default="CN")
    latitude = models.DecimalField(max_digits=10, decimal_places=6, blank=True, null=True)
    longitude = models.DecimalField(max_digits=10, decimal_places=6, blank=True, null=True)
    location = models.CharField(max_length=255, blank=True)

    class Meta:
        abstract = True

    def has_avatar(self):
        return Avatar.objects.filter(user=self.user, valid=True).count()

    def __unicode__(self):
        return _("%s's profile") % self.user

    def get_absolute_url(self):
        return reverse("profile_public", args=[self.user])


class Avatar(models.Model):
    """
    Avatar model
    """
    image = models.ImageField(upload_to="upload/member/avatars/%Y/%b/%d")
    user = models.ForeignKey(User)
    date = models.DateTimeField(auto_now_add=True)
    valid = models.BooleanField()

    class Meta:
        unique_together = (('user', 'valid'),)

    def __unicode__(self):
        return _("%s's Avatar") % self.user

    def delete(self):
        base, filename = os.path.split(self.image.path)
        name, extension = os.path.splitext(filename)
        for key in AVATAR_SIZES:
            try:
                os.remove(os.path.join(base, "%s.%s%s" % (name, key, extension)))
            except:
                pass

        super(Avatar, self).delete()

    def save(self):
        for avatar in Avatar.objects.filter(user=self.user, valid=self.valid).exclude(id=self.id):
            base, filename = os.path.split(avatar.image.path)
            name, extension = os.path.splitext(filename)
            for key in AVATAR_SIZES:
                try:
                    os.remove(os.path.join(base, "%s.%s%s" % (name, key, extension)))
                except:
                    pass
            avatar.delete()

        super(Avatar, self).save()


class EmailValidationManager(models.Manager):
    """
    Email validation manager
    """
    def verify(self, key):
        try:
            verify = self.get(key=key)
            if not verify.is_expired():
                verify.user.email = verify.email
                verify.user.save()
                verify.delete()
                return True
            else:
                verify.delete()
                return False
        except:
            return False

    def getuser(self, key):
        try:
            return self.get(key=key).user
        except:
            return False

    def add(self, user, email):
        """
        Add a new validation process entry
        """
        while True:
            key = User.objects.make_random_password(70)
            try:
                EmailValidation.objects.get(key=key)
            except EmailValidation.DoesNotExist:
                self.key = key
                break
        if settings.SEND_REGISTER_MAIL:
            template_body = "member/email/validation.txt"
            template_subject = "member/email/validation_subject.txt"
            site_name, domain = Site.objects.get_current().name, Site.objects.get_current().domain
            body = loader.get_template(template_body).render(Context(locals()))
            subject = loader.get_template(template_subject).render(Context(locals())).strip()
            send_mail(subject=subject, message=body, from_email=None, recipient_list=[email])
        user = User.objects.get(username=str(user))
        self.filter(user=user).delete()
        return self.create(user=user, key=key, email=email)

class EmailValidation(models.Model):
    """
    Email Validation model
    """
    user = models.ForeignKey(User, unique=True)
    email = models.EmailField(blank=True)
    key = models.CharField(max_length=70, unique=True, db_index=True)
    created = models.DateTimeField(auto_now_add=True)
    objects = EmailValidationManager()

    def __unicode__(self):
        return _("Email validation process for %(user)s") % { 'user': self.user }

    def is_expired(self):
        return (datetime.datetime.today() - self.created).days > 0

    def resend(self):
        """
        Resend validation email
        """
        if settings.SEND_REGISTER_MAIL:
            template_body = "member/email/validation.txt"
            template_subject = "member/email/validation_subject.txt"
            site_name, domain = Site.objects.get_current().name, Site.objects.get_current().domain
            key = self.key
            body = loader.get_template(template_body).render(Context(locals()))
            subject = loader.get_template(template_subject).render(Context(locals())).strip()
            send_mail(subject=subject, message=body, from_email=None, recipient_list=[self.email])
        self.created = datetime.datetime.now()
        self.save()
        return True

class UserProfileMediaNotFound(Exception):
    pass


# add by huaitwooos@gmail.com
GENDER_CHOICES = ( ('F', _('Female')), ('M', _('Male')),)
BLOODGROUP_CHOICES= (
    ('A',  _('A TYPE')),
    ('B',  _('B TYPE')),
    ('AB', _('AB TYPE')),
    ('O',  _('O TYPE')),
    ('R',  _('OTHER TYPE')),
    )

ZODIAC_CHOICES=(
    ('RAT',      _('Rat')),
    ('OX',       _('Ox')),
    ('TIGER',    _('Tiger')),
    ('RABBIT',   _('Rabbit')),
    ('DRAGON',   _('Dragon')),
    ('SNAKE',    _('Snake')),
    ('HORSE',    _('Horse')),
    ('GOAT',     _('Goat')),
    ('MONKEY',   _('Monkey')),
    ('ROOSTER',  _('Rooster')),
    ('DOG',      _('Dog')),
    ('PIG',      _('Pig')),
    )

CONSTELLATION_CHOICES=(
    ('ARIES',       _('Aries(the Ram)')),
    ('TAURUS',      _('Taurus(the Bull)')),
    ('GEMINI',      _('Gemini(the Twins)')),
    ('CANCER',      _('Cancer(the Crab)')),
    ('LEO',         _('Leo(the Lion)')),
    ('VIRGO',       _('Virgo(the Virgin)')),
    ('LIBRA',       _('Libra(the Scales)')),
    ('SCORPIO',     _('Scorpio(the Scorpion)')),
    ('SAGITTALIUS', _('Sagittarius(the Archer)')),
    ('CAPRICORNUS', _('Capricornus(the Goat)')),
    ('AQUALIUS',    _('Aquarius(the Water Carrier)')),
    ('PISCES',      _('Pisces(the Fishes)')),
    )

# Create your models here.

		

class ProfileManager(models.Manager):
    """
    Custom manager for the ``RegistrationProfile`` model.
    
    The methods defined here provide shortcuts for account creation
    and activation (including generation and emailing of activation
    keys), and for cleaning out expired inactive accounts.
    
    """
        
    def create_user(self, username, password, email,send_email=settings.REQUIRE_EMAIL_CONFIRMATION):
        """
       ``user``
            The ``User`` to relate the profile to.
        
        """
        new_user = User.objects.create_user(username, email, password)
        new_user.save()        
        profile = self.create_profile(new_user)
        
        return new_user
    
    def create_profile(self, user):
        """
        Create a ``Profile`` for a given ``User``, and return the ``Profile``.
        """

        return self.create(user=user,nickname=user.username,foreigname=user.username)
        

class Profile(BaseProfile):

    firstname      = models.CharField(verbose_name='名字',max_length=255, blank=True)
    surname        = models.CharField(verbose_name='姓氏',max_length=255, blank=True)
    nickname       = models.CharField(verbose_name='昵称',null=True,max_length=20)
    foreigname     = models.CharField(verbose_name='英文名',null=True,max_length=20)
    birthday       = models.DateField(verbose_name='生日',null=True,default=datetime.date.today(), blank=True)
    gender         = models.CharField(verbose_name='性别',null=True,max_length=1, choices=GENDER_CHOICES, blank=True)
    bloodgroup     = models.CharField(verbose_name='血型',null=True,max_length=4, choices=BLOODGROUP_CHOICES,blank=True)
    zodiac         = models.CharField(verbose_name='属相',null=True,max_length=20, choices=ZODIAC_CHOICES,blank=True)
    constellation  = models.CharField(verbose_name='星座',null=True,max_length=20, choices=CONSTELLATION_CHOICES,blank=True)
    height         = models.CharField(verbose_name='身高',null=True,max_length=4,blank=True)
    weight         = models.CharField(verbose_name='体重',null=True,max_length=4,blank=True)
    homeplace      = models.CharField(verbose_name='家乡',null=True,max_length=20,blank=True)
    hobby          = models.CharField(verbose_name='爱好',null=True,max_length=20,blank=True)
    character      = models.CharField(verbose_name='性格',null=True,max_length=20,blank=True)
    profession     = models.CharField(verbose_name='专业',null=True,max_length=20,blank=True)
    career         = models.CharField(verbose_name='职业',null=True,max_length=20,blank=True)

templates/member/profile/overview.html
{% extends "member/base_2col.html" %}
{% load i18n %}

{% block title %}{% trans "Overview of your profile" %}{% endblock %}
{% block robots %}noindex,nofollow{% endblock %}

{% block js.custom %}
{% if GOOGLE_MAPS_API_KEY and user.get_profile.location %}
  <script src="http://maps.google.com/maps?file=api&amp;v=2.x&amp;key={{ GOOGLE_MAPS_API_KEY }}" type="text/javascript"></script>
  <script type="text/javascript">
    $(function() {
      if (GBrowserIsCompatible()) {
        this.map = new GMap2(document.getElementById("location"));
        this.map.disableDragging();
        this.map.setCenter(new GLatLng({{ user.get_profile.latitude|default:"30" }}, {{ user.get_profile.longitude|default:"0" }}), 2);
        this.marker = new GMarker(new GLatLng({{ user.get_profile.latitude }}, {{ user.get_profile.longitude }}), {clickable: false, draggable: false});
        this.map.addOverlay(this.marker);
      }
    });
  </script>
{% endif %}
{% endblock %}



{% block userprofile_content %}
	{% load avatars %}
	<form class="yform" action="" method="post">
	<fieldset>
		<legend>你的个人档案概要</legend>
		<div id="avatar" class="span-3 center">
			<a href="{% url profile_edit_avatar %}">
				<img class="border" src="{% avatar 96 %}" />
			</a>
			<p><a href="{{ request.path_info }}edit/avatar/">{% if user.get_profile.has_avatar %}改变头像{% else %}添加头像{% endif %}</a></p>
		</div>
	
		<div class="span-9 last">
			<p><label for="id_user">{% trans "Username:" %}</label> {{ user }}</p>
			<p><label for="id_email">{% trans "E-mail:" %}</label>
				<span class="{% if not email or not validated %}quiet red{% endif %}">
				{%if not email %}还未设置
				{% else %}{{ email }}
				{% if not validated %}未确认
				{% endif %}{% endif %}
				</span>
			</p>
			<p>
			<label for="location">国家:</label>
			{% if user.get_profile.country %}
				{{ user.get_profile.get_country_display }}
			{% else %}
				<span class="quiet red">未设置</span>
			{% endif %}
			</p>
			{% if GOOGLE_MAPS_API_KEY %}
			<p>
			<label for="location">地理位置:</label>
			{% if user.get_profile.location %}
				{{ user.get_profile.location }}
			{% else %}
				<span class="quiet red">未设置</span>
			{% endif %}
			</p>
			{% endif %}
		</div>

		<hr class="space" />
		{% if user.get_profile.location %}
		<div class="span-12 last">
			<div id="location" style="width: 480px; height: 240px;"></div>
		</div>
		{% endif %}
	</fieldset>
	</form>
{% endblock %}

{% block userprofile_content_related %}
	<div class="box">
		<h3>管理</h3>
		<a href="{% url password_change %}">更改密码</a>
		<br />
		<a href="{% url email_validation %}">{% if email %}改变您的 Email 地址{% else %}添加您的 Email 地址{% endif %}</a>
		{% if not validated and email %}<br /><a href="{% url email_validation_reset %}">重新发送认证邮件</a>
		{% endif %}
		<br />
		{% if not user.get_profile.location %}
			<a href="{% url profile_edit_location %}">添加您的地理位置</a>
		{% else %}
			<a href="{% url profile_edit_location %}">改变您的地理位置</a>
		{% endif %}
	</div>
{% endblock %}

templates/member/profile/public.html
{% extends "member/base_2col.html" %}
{% load i18n %}
{% load avatars %}

{% block title %}{{ profile.user }}'s public profile{% endblock %}
{% block robots %}noindex,nofollow{% endblock %}

{% block js.custom %}
	{% if profile.latitude and profile.longitude %}
	<script type="text/javascript" src="http://www.google.com/jsapi?key={{ GOOGLE_MAPS_API_KEY }}"></script>
	<script type="text/javascript">google.load("maps", "2");</script>
	<script type="text/javascript">
		$(function() {
		if (google.maps.BrowserIsCompatible()) {
			var map = new google.maps.Map2(document.getElementById("map"));
      map.disableDragging();
			map.setCenter(new google.maps.LatLng({{ profile.latitude }}, {{ profile.longitude }}), 4);
			var marker = new google.maps.Marker(new google.maps.LatLng({{ profile.latitude }}, {{ profile.longitude }}), {clickable: false });
			map.addOverlay(marker);
		}
		});
	</script>
	{% endif %}
{% endblock %}



{% block userprofile_content %}
	<h2>{% blocktrans with profile.user as user %} {{ user }} 的公开小档案{% endblocktrans %}</h2>

	<div class="vcard">
		<!--header -->
		<div class="boxc-gray mb-20">
			<h5>{{ profile.user }}</h5>
			<p class="icaption_right"><img class="border top" alt="{{ profile.user }}" src="{% avatar 256 profile.user %}" /></p>
			<p> {{profile.intro}}</p>
		</div>
		<!--end  header -->
		
        <!--info -->
        <div class="clearfix"><ul>
            <li><span class="ico-adduser">认识了 <a href="/member/friends/list/413907/">{{ profile.total_friends }}个朋友</a></span></li>
            <li><span class="ico-photo">上传了 <a href="/photo/albums/413907/">70张照片</a></span></li>
            <li><span class="ico-post">发表了 <a href="/forum/">{{ profile.get_posts.count }}篇帖子</a></span></li>
            <li><span class="ico-blog">写出了 <a href="/blog/">{{ profile.total_blogs }}篇日记</a></span></li>
            <li><span class="ico-group">参加了 <a href="/group/7/">{{ profile.total_groups }}个团</a></span></li>
        </ul></div>
        <!--end info -->

        <div class="clearfix">

              想了解更多关于 <strong>{{ profile.user }}</strong> 的信息？            
              请<a href="{% url signup %}">注册新用户</a>


                </div>

        <div>
            已经是会员了？请 <a href="{%url login%}">登录</a></div>


	  {% if profile.latitude and profile.longitude %}
		<div class="span-10">
			<div id="map"></div>
		</div>
		{% endif %}
		
		
	</div>
	

{% endblock %}

{% block userprofile_content_related %}
        <!--friends -->
        <div class="clearfix">
            <h6>{{ profile.user }}的一些朋友...</h6>

            <table width="100%" border="0" cellspacing="10" cellpadding="0" class="fs-12">
                <tr>
                    <td valign="middle" align="center">
                    <a href="/member/profile/70461/">
                    <img src="{{MEDIA_URL}}/member/avator/user/64/70461.jpg" /></a>
                    <div class="mt-5"><a href="/member/profile/70461/">{{user}}</a></div></td>                   
                </tr>
            </table>
        </div>

        <!--end friends -->
{% endblock %}